/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cp2labproject;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class CompanyPage extends javax.swing.JFrame {

    public JLabel getIsimLabel() {
        return isimlbl;
    }

    public JLabel getusernameLabel() {
        return username;
    }

    public JLabel getincomeLabel() {
        return incomelbl;
    }

    public JLabel gettaxLabel() {
        return taxlbl;
    }

    public JLabel getIDlabel() {
        return IDlbl;
    }

    public CompanyPage() {
        initComponents();

    }
/**
 * CompanyPage sınıfı, bir şirketin bilgilerini görüntüleyen ve vergi ödeme işlemlerini yöneten bir Swing penceresini temsil eder.
 * 
 * @param name      Şirketin ismi
 * @param Username  Şirketin kullanıcı adı
 * @param income    Şirketin geliri
 * @param tax       Şirketin ödemesi gereken vergi miktarı
 * @param ID        Şirketin ID numarası
 */
    public CompanyPage(String name, String Username, String income, String tax, String ID) {
        this.isimlbl.setText(name);
        this.username.setText(Username);
        this.incomelbl.setText(income);
        this.IDlbl.setText(ID);
        this.taxlbl.setText(tax);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isimlbl = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        incomelbl = new javax.swing.JLabel();
        IDlbl = new javax.swing.JLabel();
        exitlbl = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblincome = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        taxlbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Company Page");

        exitlbl.setBackground(new java.awt.Color(153, 153, 153));
        exitlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitlbl.setForeground(new java.awt.Color(255, 255, 255));
        exitlbl.setText("LogOut");
        exitlbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitlblActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Username");

        lblincome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblincome.setText("Your Income");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Your Tax Value");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Your ID number");

        jMenu1.setText("Notification");

        jMenuItem1.setText("check tax");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 277, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblincome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(isimlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(incomelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitlbl)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isimlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(incomelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblincome, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitlblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitlblActionPerformed

        int YesOrNo = JOptionPane.showConfirmDialog(null, "Do you want to exit?", "LogOut", JOptionPane.YES_NO_OPTION);
        if (YesOrNo == 0) {
            dispose();
            UserLogin loginpage = new UserLogin();
            loginpage.setVisible(true);
        }
    }//GEN-LAST:event_exitlblActionPerformed
/**
 * Notification menüsündeki "check tax" seçeneğine tıklandığında gerçekleşen olay.
 */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        // TODO add your handling code here:
        String idText = IDlbl.getText();

        if (!idText.isEmpty()) {
            try {
                int id = Integer.parseInt(idText);
                String message = getNotificationMessage(id);
                if (message == null) {
                    JOptionPane.showMessageDialog(this, "There is no message", "Notification", JOptionPane.INFORMATION_MESSAGE);
                } else if (message.contains("Tax is paid.")) {
                    JOptionPane.showMessageDialog(this, message, "Notification", JOptionPane.INFORMATION_MESSAGE);
                } else if (message.contains("Tax is postponed.")) {
                    JOptionPane.showMessageDialog(this, message, "Notification", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // Kullanıcıya Yes/No seçeneğiyle mesajı göster
                    int option = JOptionPane.showConfirmDialog(this, message, "Notification", JOptionPane.YES_NO_OPTION);

                    if (option == JOptionPane.YES_OPTION) {
                        int taxValue = extractTaxValueFromMessage(message);

                        // Convert taxValue to int
                        int intTaxValue = (int) taxValue;

                        // taxlbl içindeki değeri güncelle
                        taxlbl.setText(Integer.toString(intTaxValue));

                        // incomelbl içindeki değeri al
                        int income = Integer.parseInt(incomelbl.getText());

                        // Yeni tax değerini income'den çıkar
                        int newIncome = income - intTaxValue;

                        // incomelbl içine yeni değeri yaz
                        incomelbl.setText(Integer.toString(newIncome));

                        // Veritabanını güncelle
                        updateCompanyTaxAndIncome(id, newIncome, intTaxValue);

                        // Notification mesajını güncelle
                        updateNotificationMessage(id, "Tax is paid.");
                    } else {
                        // Notification mesajını güncelle
                        updateNotificationMessage(id, "The tax is postponed.");
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Invalid ID format: " + idText);
                // Handle the error or provide user feedback
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "ID is empty.");
            // Handle the case where ID is empty

        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed
/**
 * Dosyaya yazma işlemini gerçekleştiren yardımcı bir yöntem.
 * 
 * @param filename  Yazılacak dosyanın adı
 * @param content   Dosyaya yazılacak içerik
 */
    /**
     * @param args the command line arguments
     */
    private void writeToFile(String filename, String content) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filename, true))) {
            writer.write(content);
            writer.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
/**
 * Mesaj içerisinden vergi değerini çıkaran yardımcı bir yöntem.
 * 
 * @param message   Mesaj içeriği
 * @return          Çıkartılan vergi değeri
 */
    public int extractTaxValueFromMessage(String message) {
        // "which is" ifadesinden sonraki sayıyı al
        String[] parts = message.split("which equals to");
        if (parts.length > 1) {
            String numberPart = parts[1].trim();
            return Integer.parseInt(numberPart);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error while execute.");
            return 0;
        }

    }

    public void updateCompanyTaxAndIncome(int id, int newIncome, int taxValue) {
        String tableName = "company";

        String query = "UPDATE " + tableName + " SET income = ?, tax = ? WHERE id = ?";

        String url = "jdbc:mysql://localhost:3306/fzt"; // Veritabanı adınızı burada belirtin
        String username = "root"; // Kullanıcı adınızı burada belirtin
        String password = "fsmvu"; // Parolanızı burada belirtin

        try (Connection connection = DriverManager.getConnection(url, username, password); PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setInt(1, newIncome);
            preparedStatement.setInt(2, taxValue);
            preparedStatement.setInt(3, id);

            int rowsUpdated = preparedStatement.executeUpdate();

            if (rowsUpdated > 0) {
                System.out.println("Şirket vergi ve geliri başarıyla güncellendi!");
            } else {
                System.out.println("Şirket vergi ve geliri güncelleme başarısız.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            // SQLException'ı ele alarak hata mesajını ve ayrıntılarını görüntüleyebilirsiniz.
        }
    }

    public void updateNotificationMessage(int id, String newMessage) {
        // Veritabanında ilgili ID'ye sahip notification kaydının mesajını güncelle
        String url = "jdbc:mysql://127.0.0.1:3306/fzt";
        String username = "root";
        String password = "fsmvu";
        id = id + 100;

        try (Connection connection = DriverManager.getConnection(url, username, password); PreparedStatement preparedStatement = connection.prepareStatement("UPDATE notificationstable SET messages = ? WHERE id = ?")) {

            preparedStatement.setString(1, newMessage);
            preparedStatement.setInt(2, id);

            int rowsUpdated = preparedStatement.executeUpdate();

            if (rowsUpdated > 0) {
                System.out.println("Notification message updated successfully!");
            } else {
                System.out.println("Notification message update failed.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public String getNotificationMessage(int id) {
        String message = null;
        id = id + 100;

        // Veritabanından ilgili ID'ye sahip notification mesajını al
        String url = "jdbc:mysql://127.0.0.1:3306/fzt";
        String username = "root";
        String password = "fsmvu";

        try (Connection connection = DriverManager.getConnection(url, username, password); PreparedStatement preparedStatement = connection.prepareStatement("SELECT messages FROM notificationstable WHERE id = ?")) {

            preparedStatement.setInt(1, id);

            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    message = resultSet.getString("messages");
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        return message;
    }

    public static void main(String args[]) {

        Company company = new Company();

        JLabel isimlbl = new JLabel();
        isimlbl.setText(company.getName());
        JLabel usernamelbl = new JLabel();
        usernamelbl.setText(company.getUsername());
        JLabel incomelbl = new JLabel();
        int income = company.getIncome();
        String incomeString = Integer.toString(income);
        incomelbl.setText(incomeString);
        JLabel taxlbl = new JLabel();

        int tax = company.getTax();
        String taxString = Integer.toString(tax);
        taxlbl.setText(taxString);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CompanyPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDlbl;
    private javax.swing.JButton exitlbl;
    private javax.swing.JLabel incomelbl;
    private javax.swing.JLabel isimlbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblincome;
    private javax.swing.JLabel taxlbl;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
