/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cp2labproject;


import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static com.mycompany.cp2labproject.AdminPage.companymodel;
import java.sql.PreparedStatement;

/**
 *
 * @author dell
 */
public class ManagerPage extends javax.swing.JFrame {

    public JLabel getIsimLabel() {
        return NameLBL;
    }

    public JLabel getSoyIsimLabel() {
        return SurnameLBL;
    }

    public JLabel getIDlabel() {
        return IDlbl;
    }

    /**
     * Creates new form ManagerPage
     */
    public ManagerPage() {
        // ManagerPage oluşturulduğunda bileşenleri başlat
        initComponents(); 
    }
// Veritabanı bağlantı bilgileri
     String url = "jdbc:mysql://127.0.0.1:3306/fzt ";
        String username = "root"; // Kullanıcı adını buraya girin
        String password = "fsmvu";

// Şirket verilerini tabloya yükleme metod
    private void loadCompanyData() {
        // Tablo sütunlarını ayarla
        companymodel.setColumnIdentifiers(new String[]{"ID", "Name", "Username", "Income", " Tax"});
        companymodel.setRowCount(0);

        try ( Connection connection = DriverManager.getConnection(url, username, password);  Statement statement = connection.createStatement();  ResultSet resultSet = statement.executeQuery("SELECT * FROM company")) {

            while (resultSet.next()) {
                 // Sonuç kümesinden verileri al
                String id = resultSet.getString("id");
                String name = resultSet.getString("name");
                String Username = resultSet.getString("username");
                String income = resultSet.getString("income");
                String tax = resultSet.getString("tax");
                // Verileri tablo modeline ekle
                companymodel.addRow(new Object[]{id, name, Username, income, tax});
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    // Şirket verilerini bir metin dosyasına yazma metod
    private void writeDataToTextFile() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("company_data.txt"))) {
            // Başlık satırını yaz
            writer.write("ID\tName\tUsername\tIncome\tTax\n");
        // Verileri yazmak için satır ve sütunlarda döngü
            for (int i = 0; i < companymodel.getRowCount(); i++) {
                StringBuilder rowData = new StringBuilder();
                for (int j = 0; j < companymodel.getColumnCount(); j++) {
                    rowData.append(companymodel.getValueAt(i, j));
                    if (j < companymodel.getColumnCount() - 1) {
                        rowData.append("\t"); // Sutunlar arasına sekme karakteri ekler
                    }
                }
                writer.write(rowData.toString());
                writer.newLine(); // Yeni bir satıra geçer
            }
            
            System.out.println("Veriler başarıyla dosyaya yazıldı: company_data.txt");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        companybl = new javax.swing.JTable();
        rfrshbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NameLBL = new javax.swing.JLabel();
        IDlbl = new javax.swing.JLabel();
        SurnameLBL = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        surnametxt = new javax.swing.JTextField();
        IDtxt = new javax.swing.JTextField();
        NameLBL1 = new javax.swing.JLabel();
        SurnameLBL1 = new javax.swing.JLabel();
        IDlbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Usercombo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        btnPrintSelectedCompany = new javax.swing.JButton();
        btnPrintAllCompanies = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Surname");

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Page");

        companybl.setBackground(new java.awt.Color(204, 204, 204));
        companybl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null"
            }
        ));
        jScrollPane1.setViewportView(companybl);

        rfrshbtn.setBackground(new java.awt.Color(102, 0, 153));
        rfrshbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rfrshbtn.setForeground(new java.awt.Color(255, 255, 255));
        rfrshbtn.setText("Refresh Company List");
        rfrshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfrshbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Surname");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Your ID number");

        jLabel1.setText("Enter Manager Name");

        jLabel2.setText("Enter Manager Surname");

        jLabel3.setText("Enter Manager ID");

        Usercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Click for selection", "Add Manager", "Delete Manager", "Find Manager by ID", "Update Manager" }));
        Usercombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsercomboActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Apply");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnPrintSelectedCompany.setText("Print Selected Company");
        btnPrintSelectedCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintSelectedCompanyActionPerformed(evt);
            }
        });

        btnPrintAllCompanies.setText("Print All Companies");
        btnPrintAllCompanies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintAllCompaniesActionPerformed(evt);
            }
        });

        jMenu1.setBackground(new java.awt.Color(0, 0, 204));
        jMenu1.setText("LogOut And Company Affairs");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("LogOut");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Cmp. Afr.");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rfrshbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SurnameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SurnameLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8)
                                .addComponent(surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(IDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(IDlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NameLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(23, 23, 23)
                                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Usercombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(176, 176, 176))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrintSelectedCompany)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrintAllCompanies)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SurnameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(SurnameLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(7, 7, 7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(IDlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rfrshbtn)
                                    .addComponent(btnPrintSelectedCompany)
                                    .addComponent(btnPrintAllCompanies)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Usercombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addGap(81, 81, 81)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rfrshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfrshbtnActionPerformed
           // Şirket verilerini yeniden yükleme butonuna tıklanınca
        loadCompanyData();
        companybl.setModel(companymodel);
    }//GEN-LAST:event_rfrshbtnActionPerformed

    private void UsercomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsercomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsercomboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (Usercombo.getSelectedIndex() == 0) {
                    // Kullanıcı bir seçenek seçmediğinde uyarı göster
            JOptionPane.showMessageDialog(rootPane, "Please select one of them.");
        }
        if (Usercombo.getSelectedIndex() == 1) {
                    // Kullanıcı "Yönetici Ekle" seçeneğini seçtiğinde
            String name = nametxt.getText();
            String surname = surnametxt.getText();
            String str = IDtxt.getText(); // Metottan gelen string değer
            int ID = Integer.parseInt(str);

            addManager (name, surname, ID);
            JOptionPane.showMessageDialog(rootPane, "The manager has been added.");
        }
        if (Usercombo.getSelectedIndex() == 2) {
                    // Kullanıcı "Yönetici Sil" seçeneğini seçtiğinde
            String str = IDtxt.getText(); // Metottan gelen string değer
            int ID = Integer.parseInt(str);
            deleteManager (ID);

            JOptionPane.showMessageDialog(rootPane, "The manager has been removed.");
        }
        if (Usercombo.getSelectedIndex() == 3) {
                     // Kullanıcı "ID'ye Göre Yönetici Bul" seçeneğini seçtiğinde
             String str = IDtxt.getText(); // Metottan gelen string değer
                int ID = Integer.parseInt(str);
            
            findManagerByID(ID);
            
           
        }
        if (Usercombo.getSelectedIndex() == 4) {
                    // Kullanıcı "Yönetici Güncelle" seçeneğini seçtiğinde
            String name = nametxt.getText();
            String surname = surnametxt.getText();
            String str = IDtxt.getText(); // Metottan gelen string değer
            int ID = Integer.parseInt(str);
            updateManager(name, surname, ID);
            JOptionPane.showMessageDialog(rootPane, "The selected manager has been updated.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
            // "Çıkış Yap" seçeneğine tıklanınca
        int YesOrNo = JOptionPane.showConfirmDialog(null, "Do you want to exit?", "LogOut", JOptionPane.YES_NO_OPTION);
        if (YesOrNo == 0) {
                    // Onaylandığında pencereyi kapat ve kullanıcı giriş sayfasını aç
            dispose();
            UserLogin loginpage = new UserLogin();
            loginpage.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
            // "Şirket Ekle" seçeneğine tıklanınca
        CompanyAddForManager frame = new CompanyAddForManager();
        frame.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void btnPrintAllCompaniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintAllCompaniesActionPerformed
        // TODO add your handling code here:
        
        writeDataToTextFile();
        
    }//GEN-LAST:event_btnPrintAllCompaniesActionPerformed

    private void btnPrintSelectedCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintSelectedCompanyActionPerformed
        // Seçilen satırın verilerini dosyaya yaz
int selectedRowIndex = companybl.getSelectedRow();
                if (selectedRowIndex != -1) {
                    writeSelectedRowToTextFile(selectedRowIndex);
                } else {
                    JOptionPane.showMessageDialog(null, "Lütfen bir satır seçin.", "Uyarı", JOptionPane.WARNING_MESSAGE);
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintSelectedCompanyActionPerformed

    private void writeSelectedRowToTextFile(int selectedRowIndex) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("selected_row.txt"))) {
            // Verileri JTable'dan al
            String id = (String) companymodel.getValueAt(selectedRowIndex, 0);
            String name = (String) companymodel.getValueAt(selectedRowIndex, 1);
            String username = (String) companymodel.getValueAt(selectedRowIndex, 2);
            String income = (String) companymodel.getValueAt(selectedRowIndex, 3);
            String tax = (String) companymodel.getValueAt(selectedRowIndex, 4);

            // Verileri dosyaya yaz
            writer.write("ID: " + id);
            writer.newLine();
            writer.write("Name: " + name);
            writer.newLine();
            writer.write("Username: " + username);
            writer.newLine();
            writer.write("Income: " + income);
            writer.newLine();
            writer.write("Tax: " + tax);
            writer.newLine();

            JOptionPane.showMessageDialog(null, "Seçilen satır başarıyla dosyaya yazıldı: selected_row.txt", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Dosya yazma hatası oluştu.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
 
    
    
    
     public void addManager (String name, String surname, int ID) {
        String sql = "INSERT INTO manager (id, name, surname) VALUES (?, ?, ?)";

        try (Connection connection = DriverManager.getConnection(url, username, password);
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setInt(1, ID);
            preparedStatement.setString(2, name);
            preparedStatement.setString(3, surname);

            int rowsInserted = preparedStatement.executeUpdate();
            if (rowsInserted > 0) {
                System.out.println("A new manager was inserted successfully!");
            }
        } catch (SQLException e) {
            if (e instanceof SQLIntegrityConstraintViolationException) {
                System.err.println("You cannot enter the same ID!");
            } else {
                e.printStackTrace();
            }
        }
    }
    
    public void updateManager(String name, String surname, int ID) {
        String sql = "UPDATE manager SET name = ?, surname = ? WHERE id = ?";

        try (Connection connection = DriverManager.getConnection(url, username, password);
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setString(1, name);
            preparedStatement.setString(2, surname);
            preparedStatement.setInt(3, ID);

            int rowsUpdated = preparedStatement.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("Manager with ID " + ID + " was updated successfully!");
            } else {
                System.out.println("No manager found with ID " + ID);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void deleteManager (int ID) {
        String sql = "DELETE FROM manager WHERE id = ?";

        try (Connection connection = DriverManager.getConnection(url, username, password);
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setInt(1, ID);

            int rowsDeleted = preparedStatement.executeUpdate();
            if (rowsDeleted > 0) {
                System.out.println("Manager with ID " + ID + " was deleted successfully!");
            } else {
                System.out.println("No manager found with ID " + ID);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
     public void findManagerByID(int ID) {
        String sql = "SELECT name, surname FROM manager WHERE id = ?";

        try (Connection connection = DriverManager.getConnection(url, username, password);
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setInt(1, ID);

            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    String name = resultSet.getString("name");
                    String surname = resultSet.getString("surname");

                    String message = "Name: " + name + "\nSurname: " + surname + "\nID: " + ID;
                    JOptionPane.showMessageDialog(null, message, "Manager Information", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "There is no manager with this ID.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
  

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDlbl;
    private javax.swing.JLabel IDlbl1;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JLabel NameLBL;
    private javax.swing.JLabel NameLBL1;
    private javax.swing.JLabel SurnameLBL;
    private javax.swing.JLabel SurnameLBL1;
    private javax.swing.JComboBox<String> Usercombo;
    private javax.swing.JButton btnPrintAllCompanies;
    private javax.swing.JButton btnPrintSelectedCompany;
    private javax.swing.JTable companybl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton rfrshbtn;
    private javax.swing.JTextField surnametxt;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
